# Backend Cloud Build Configuration
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/mama-bear-backend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/mama-bear-backend:latest',
      '.'
    ]
    dir: 'backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mama-bear-backend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mama-bear-backend:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'mama-bear-backend',
      '--image', 'gcr.io/$PROJECT_ID/mama-bear-backend:$COMMIT_SHA',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--timeout', '300',
      '--concurrency', '80',
      '--set-env-vars', 'FLASK_ENV=production,PYTHONPATH=/app'
    ]

images:
  - 'gcr.io/$PROJECT_ID/mama-bear-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/mama-bear-backend:latest'
